# fly.toml file generated for pickit on 2023-08-28T22:41:36+07:00

app = "pickit"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
